version: '3.7'
services:
  db:
    image: postgres:12
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data

    networks:
      - local
  app:
    build: .
    command:  flask run -h 0.0.0.0 -p 80
    restart: on-failure
    environment:
      - FLASK_APP=src/main.py
      - FLASK_DEBUG=1
      - FLASK_ENV=docker
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:80:80"
    depends_on: 
      - db
    networks:
      - local
  adminer:
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    networks:
      - local

networks:
  local:
    driver: bridge